### PR TITLE
add rule for too many test cases in test suite

### PR DESCRIPTION
**Pull request by guykisel**
This is based on the rule in https://code.google.com/p/robotframework/wiki/HowToWriteGoodTestCases#Test_suite_structure

"Should not have too many tests (max 10) in one suite unless they are data-driven."

Example output:

    W: 12, 0: Too many test cases (29) in test suite (TooManyTestCases)

### CODE REVIEW

**Comment by boakley** [comment]
I'd like to include this rule, but I want it to be configurable. (see [Configurable Rules](https://github.com/boakley/robotframework-lint/wiki/How-to-write-custom-rules#configurable-rules) on the wiki). I'll be glad to make it configurable if you want, or you can do it yourself. 

Sorry it took so long for me to respond.

**Comment by guykisel** [comment]
No problem. I'll make the necessary changes.

**Comment by guykisel** [comment]
Updated.

(also I think if you want Travis CI to run on pull requests you need to log into Travis with your github credentials and switch it from "off" to "on" for this project)

**Comment by boakley** [comment]
Thanks, Guy!

**Comment by boakley** [comment]
I hope you don't mind, but I edited this rule to point to the Nth test case. For example, if the max is 10 and there are more than 10, the line number should point to test 11 since that's where the problem begins. Does that make sense?

**Comment by guykisel** [comment]
Yeah, that sounds great.

**Pull request merged**
