### PR TITLE
add rule for too many steps in test case

### PR DESCRIPTION
**Pull request by guykisel**
Based on https://code.google.com/p/robotframework/wiki/HowToWriteGoodTestCases#Workflow_tests

"Max 10 steps, preferably less"

Example output:

    W: 173, 0: Too many steps (13) in test case (TooManyTestSteps)

### CODE REVIEW

**Comment by boakley** [comment]
I'd like to include this rule, but I want it to be configurable. (see [Configurable Rules](https://github.com/boakley/robotframework-lint/wiki/How-to-write-custom-rules#configurable-rules) on the wiki). I'll be glad to make it configurable if you want, or you can do it yourself. All you need to do is add a configure method that takes a string as a parameter and sets the maximum number allowed. You can see the otherRules.py:LineTooLong rule for an example. 

Sorry it took so long for me to respond.

**Comment by guykisel** [comment]
No problem. I'll make the necessary changes.

**Comment by guykisel** [comment]
@boakley have you pushed the support for configurable rules to github yet? I can't find it in the project source, other than the reference you linked on the wiki.

**Comment by boakley** [comment]
My bad. I didn't realize I had a bunch of stuff I hadn't pushed. It should
be there now.

https://github.com/boakley/robotframework-lint/commit/441f319a

**Comment by guykisel** [comment]
Cool, thanks!

**Comment by guykisel** [comment]
@boakley I've implemented configurableness. If it looks to you like I've done it correctly, I'll do the same for my other rule PR.

**Comment by boakley** [comment]
Cool. I'll try to take a look at it this weekend.

**Pull request merged**
