### PR TITLE
added python3 support

### PR DESCRIPTION
**Pull request by JackTheSparrow**
Hi! As you know Robot Framework has supported Python 3 for about a year and it would be great if robotframework-lint also supports Python 3. I've made some changes in the source code so the linter could be used with Python 2 and Python 3. I tested it with Python 2.7, 3.3, 3.4 and 3.5 and it seems work OK. Please consider my changes to add them in your master branch.

### CODE REVIEW

**Comment by boakley** [comment]
Thank you!

**Comment by JackTheSparrow** [comment]
Could you please push the new version of robotframework-lint with supporting Python 3 to PyPi? I use it in my project and it'll be convenient for me to install it with pip rather than download it from github. Thank you in advance.

**Comment by boakley** [comment]
Version 0.9 has been uploaded to pypi

**Comment by JackTheSparrow** [comment]
Thank you!

**Comment by Apteryks** [comment]
> Version 0.9 has been uploaded to pypi

Just a friendly request: would it be possible to tag releases in the repo in the future? I have no idea what commit the 0.9 release available on PyPI was made from. Thanks!

**Comment by Apteryks** [comment]
I've dug the PyPI archive and it seems that 0.9 was made of commit eca94b3; based the content of the file .egg-info/pbr.json.

**Comment by Apteryks** [comment]
Based on the date of the release and the commits history, this would have to be commit: e851879bab1f63e4e53b34a4dc8a67ed95102830.  All the tests pass for this commit, unlike on the current master.

**Pull request merged**
